sudo: false
language: c
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
before_install:
  - export TRAVIS_ROOT=$HOME/travis
  - mkdir $TRAVIS_ROOT
  - ./autogen.sh
install:
  - ./configure --prefix=$TRAVIS_ROOT --disable-fortran --disable-cxx --enable-strict
  - make -j2
  - make install
  - make check # trivial tests
before_script:
  - echo "TODO: create the MPICH test suite tarball"
script:
  - echo "TODO: run MPICH test suite"
after_failure:
  - echo "Sad Panda"
notifications:
  email:
    recipients:
      - jeff.science@gmail.com
    on_success: [change]
    on_failure: [always]
